### ISSUE TITLE
你好，两个问题？第一个问题，COD不是与SOD一样属于类别无关的任务吗?那你定义这个问题的的意义何在？第二个问题，啥时候放出数据集呢，谢谢

### ISSUE THREAD

**Issue by Jack960317** [zhangxuying1004/RefCOD#2]

**Comment by zhangxuying1004** [comment]
问题1：RefCOD中提到的类别信息指的是目标物体所具备的共性信息，您可以把它视为一种protype，RefCOD基于这一信息，将传统的COD漫无目的地寻找所有潜在伪装物体的过程转换为带有特定目的的指向性物体的搜索或者匹配过程。在RefCOD推理的过程，模型是不知道上述共性信息是什么类别（比如猫、狗等）的，它只是将这一信息视为目标，找寻给定图片中与其相近的像素区域，因此这个过程是判断是/否（前景/背景），与COD/SOD类别无关的特性并不冲突。

问题2: 数据集和代码将会在接下来一周左右陆续上传到这个project，欢迎大家提出问题，开展相关研究，共同完善这个topic。

**Comment by Jack960317** [comment]
数据集怎么还没放出来啊

**Comment by zhangxuying1004** [comment]
> 数据集怎么还没放出来啊

感谢您的关注，代码和数据集已上传到project，并且我将会持续优化和更新。
