### ISSUE TITLE
about the dataloader

### ISSUE THREAD

**Issue by 1774537072** [zhangxuying1004/RefCOD#4]
Hello, thank you very much for your work, my question may be relatively simple because it is my first contact with this aspect, I would like to ask whether the value of sal_f returned in the data loading part is the text feature after processing? Do salient_ICON-R and RefFeat_ICON-R in the data set represent the truth value and class information of the reference image, respectively? I'm very sorry to bother you and hope to get your reply.

**Comment by zhangxuying1004** [comment]
> Hello, thank you very much for your work, my question may be relatively simple because it is my first contact with this aspect, I would like to ask whether the value of sal_f returned in the data loading part is the text feature after processing? Do salient_ICON-R and RefFeat_ICON-R in the data set represent the truth value and class information of the reference image, respectively? I'm very sorry to bother you and hope to get your reply.

Thanks for your attention. 
1. sal_f returns the representation value of referring images,  'sal' is the abbreviation of 'salient'. 
we have extracted object features of each referring image in advance to reduce inference time. 
2. 'salient_ICON-R' is the saliency map for masking the foreground object in referring images, and it is extracted by ICON with Resnet50 backbone. 
3. 'RefFeat_ICON-R ' is the object features of each referring image.
