### ISSUE TITLE
The link to Baidu Netdisk failed again

### ISSUE THREAD

**Issue by Rey-nard** [zhangxuying1004/RefCOD#6]
I try to download the R2C7K dataset using the link provided, but something was wrong with it. It seems that the link failed again?

**Comment by zhangxuying1004** [comment]
> I try to download the R2C7K dataset using the link provided, but something was wrong with it. It seems that the link failed again?

I'm sorry for that. I have updated the dataset link, and you can download it now.

**Comment by Rey-nard** [comment]
Thanks a lot!
